name: PR Guard
on:
  pull_request:
    paths:
      - "content/AGENT.ja.md"
      - "docs/**"
      - "i18n/**"
      - "spec/agent.schema.json"
      - "scripts/**"
      - ".github/workflows/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ドキュメント整合性チェック
        run: python scripts/validate_docs.py
      - name: Build (dry-run)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python scripts/build.py
      - name: Review (strict)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python scripts/review.py --strict
