name: ドキュメント整合性チェック

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'content/**'
      - 'scripts/validate_docs.py'
      - '.github/workflows/validate-docs.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'content/**'
      - 'scripts/validate_docs.py'

jobs:
  validate:
    name: バリデーション実行
    runs-on: ubuntu-latest
    
    steps:
    - name: チェックアウト
      uses: actions/checkout@v4
      
    - name: Python セットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 依存関係インストール
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: ドキュメント整合性チェック
      run: |
        python scripts/validate_docs.py
        
    - name: 結果サマリー
      if: always()
      run: |
        echo "## 📝 ドキュメント検証結果" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ $? -eq 0 ]; then
          echo "✅ 全てのチェックに合格しました！" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ バリデーションエラーが発生しました。" >> $GITHUB_STEP_SUMMARY
          echo "詳細はログを確認してください。" >> $GITHUB_STEP_SUMMARY
        fi
